<?php

namespace App\Http\Controllers\Releases\Agricultural\Services;

use App\Http\Controllers\Controller;
use App\Services\Releases\Inventory\ProductStockService;
use App\Services\Shared\DocumentSequenceService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;
use Illuminate\Validation\ValidationException;

class GeneralAgriculturalServiceController extends Controller
{
    public function __construct(private readonly ProductStockService $stocks,private readonly DocumentSequenceService $numbers){}
    public function index(Request $r){return DB::table('general_agricultural_services')->whereNull('deleted_at')->when($r->service_category,fn($q,$v)=>$q->where('service_category',$v))->when($r->status,fn($q,$v)=>$q->where('status',$v))->when($r->farm_id,fn($q,$v)=>$q->where('farm_id',$v))->latest('service_date')->paginate(25);}
    public function show(int $service){return $this->detail($service);}
    public function store(Request $r){$d=$r->validate($this->rules());return DB::transaction(function()use($d,$r){$id=DB::table('general_agricultural_services')->insertGetId([...collect($d)->only(['service_category','agricultural_service_type_id','crop_id','culture_id','farm_id','service_date','started_at','finished_at','notes'])->all(),'service_number'=>$this->numbers->next('SAG'),'total_area'=>0,'status'=>'DRAFT','created_by'=>$r->user()->id,'created_at'=>now(),'updated_at'=>now()]);$this->children($id,$d);return response()->json($this->detail($id),201);});}
    public function update(Request $r,int $service){$d=$r->validate($this->rules());return DB::transaction(function()use($d,$service){$row=DB::table('general_agricultural_services')->where('id',$service)->lockForUpdate()->firstOrFail();if(!in_array($row->status,['DRAFT','PLANNED']))throw ValidationException::withMessages(['status'=>['Serviço não pode mais ser alterado.']]);DB::table('agricultural_service_operators')->where('general_agricultural_service_id',$service)->delete();$plots=DB::table('agricultural_service_plots')->where('general_agricultural_service_id',$service)->pluck('id');DB::table('agricultural_service_plot_rates')->whereIn('agricultural_service_plot_id',$plots)->delete();DB::table('agricultural_service_plots')->where('general_agricultural_service_id',$service)->delete();DB::table('agricultural_input_applications')->where('general_agricultural_service_id',$service)->delete();DB::table('agricultural_service_stock_allocations')->where('general_agricultural_service_id',$service)->delete();$fire=DB::table('firebreak_maintenances')->where('general_agricultural_service_id',$service)->first();if($fire){DB::table('firebreak_maintenance_locations')->where('firebreak_maintenance_id',$fire->id)->delete();DB::table('firebreak_maintenances')->where('id',$fire->id)->delete();}DB::table('general_agricultural_services')->where('id',$service)->update([...collect($d)->only(['service_category','agricultural_service_type_id','crop_id','culture_id','farm_id','service_date','started_at','finished_at','notes'])->all(),'updated_at'=>now()]);$this->children($service,$d);return $this->detail($service);});}
    public function plan(int $service){DB::table('general_agricultural_services')->where('id',$service)->where('status','DRAFT')->update(['status'=>'PLANNED','updated_at'=>now()]);return $this->detail($service);}
    public function start(int $service){DB::table('general_agricultural_services')->where('id',$service)->whereIn('status',['DRAFT','PLANNED'])->update(['status'=>'IN_PROGRESS','started_at'=>now(),'updated_at'=>now()]);return $this->detail($service);}
    public function complete(Request $r,int $service){return DB::transaction(function()use($r,$service){$row=DB::table('general_agricultural_services')->where('id',$service)->lockForUpdate()->firstOrFail();if(!in_array($row->status,['PLANNED','IN_PROGRESS']))throw ValidationException::withMessages(['status'=>['O serviço não está disponível para finalização.']]);$allocations=DB::table('agricultural_service_stock_allocations')->where('general_agricultural_service_id',$service)->lockForUpdate()->get();if($row->service_category==='INPUT_APPLICATION'&&$allocations->isEmpty())throw ValidationException::withMessages(['stock_allocations'=>['Informe a origem e a quantidade real do produto.']]);$application=DB::table('agricultural_input_applications')->where('general_agricultural_service_id',$service)->lockForUpdate()->first();if($application){$actual=round((float)$allocations->sum('real_quantity'),3);if($actual<=0)throw ValidationException::withMessages(['stock_allocations'=>['A quantidade real aplicada deve ser maior que zero.']]);DB::table('agricultural_input_applications')->where('id',$application->id)->update(['real_quantity'=>$actual,'updated_at'=>now()]);}foreach($allocations as$a){$stock=DB::table('product_stocks')->where('id',$a->product_stock_id)->firstOrFail();if((int)$stock->product_id!==(int)$a->product_id||($application&&(int)$a->product_id!==(int)$application->product_id))throw ValidationException::withMessages(['stock_allocations'=>['O estoque selecionado não pertence ao produto do serviço.']]);$movement=$this->stocks->output(['product_id'=>$a->product_id,'stock_location_id'=>$stock->stock_location_id,'batch'=>$stock->batch,'treatment_status'=>$stock->treatment_status,'quantity'=>$a->real_quantity,'unit_value'=>$stock->average_cost,'movement_type'=>'AGRICULTURAL_SERVICE_OUTPUT','source_type'=>'GeneralAgriculturalService','source_id'=>$service,'created_by'=>$r->user()->id]);DB::table('agricultural_service_stock_allocations')->where('id',$a->id)->update(['stock_movement_id'=>$movement]);}DB::table('general_agricultural_services')->where('id',$service)->update(['status'=>'COMPLETED','completed_by'=>$r->user()->id,'completed_at'=>now(),'finished_at'=>now(),'updated_at'=>now()]);return $this->detail($service);});}
    private function children(int $id,array $d):void
    {
        $total=0;$plotIds=[];
        foreach($d['plots'] as$i=>$p){$plot=DB::table('plot_fields')->where('id',$p['plot_field_id'])->firstOrFail();$area=(float)$plot->area;$pid=DB::table('agricultural_service_plots')->insertGetId(['general_agricultural_service_id'=>$id,'plot_field_id'=>$p['plot_field_id'],'pass_number'=>$p['pass_number']??$i+1,'registered_area'=>$area,'worked_area'=>$area,'area_source'=>'REGISTRATION','notes'=>$p['notes']??null,'created_at'=>now(),'updated_at'=>now()]);$plotIds[]=$pid;$total+=$area;}
        DB::table('general_agricultural_services')->where('id',$id)->update(['total_area'=>$total]);
        foreach($d['operators'] as$o)DB::table('agricultural_service_operators')->insert([...$o,'general_agricultural_service_id'=>$id,'created_at'=>now(),'updated_at'=>now()]);
        if($d['service_category']==='INPUT_APPLICATION'){$a=$d['application'];$recommended=0;$aid=DB::table('agricultural_input_applications')->insertGetId(['general_agricultural_service_id'=>$id,'product_id'=>$a['product_id'],'rate_type'=>$a['rate_type'],'fixed_rate'=>$a['fixed_rate']??null,'rate_unit'=>$a['rate_unit'],'recommended_quantity'=>0,'real_quantity'=>$a['real_quantity']??null,'created_at'=>now(),'updated_at'=>now()]);foreach($plotIds as$i=>$pid){$rate=$a['rate_type']==='FIXED'?(float)$a['fixed_rate']:(float)$a['plot_rates'][$i]['rate'];$area=(float)DB::table('agricultural_service_plots')->where('id',$pid)->value('worked_area');$qty=$area*$rate*($a['rate_unit']==='T_HA'?1000:1);$recommended+=$qty;DB::table('agricultural_service_plot_rates')->insert(['agricultural_service_plot_id'=>$pid,'rate'=>$rate,'rate_unit'=>$a['rate_unit'],'recommended_quantity'=>$qty,'real_quantity'=>$a['plot_rates'][$i]['real_quantity']??null,'calculation_snapshot'=>json_encode(['area'=>$area,'rate'=>$rate]),'created_at'=>now(),'updated_at'=>now()]);}DB::table('agricultural_input_applications')->where('id',$aid)->update(['recommended_quantity'=>$recommended]);foreach($d['stock_allocations']??[]as$s)DB::table('agricultural_service_stock_allocations')->insert([...$s,'general_agricultural_service_id'=>$id,'product_id'=>$a['product_id'],'created_at'=>now(),'updated_at'=>now()]);}
        if($d['service_category']==='FIREBREAK_MAINTENANCE'){$f=$d['firebreak'];$fid=DB::table('firebreak_maintenances')->insertGetId(['general_agricultural_service_id'=>$id,'length_meters'=>0,'width_meters'=>$f['width_meters']??0,'calculated_area'=>0,'actual_area'=>$f['actual_area']??null,'created_at'=>now(),'updated_at'=>now()]);$length=0;$area=0;foreach($f['locations']as$i=>$l){$calculated=round(($l['length_meters']*$l['width_meters'])/10000,3);$length+=$l['length_meters'];$area+=$calculated;DB::table('firebreak_maintenance_locations')->insert([...$l,'firebreak_maintenance_id'=>$fid,'sequence'=>$i+1,'calculated_area'=>$calculated,'created_at'=>now(),'updated_at'=>now()]);}DB::table('firebreak_maintenances')->where('id',$fid)->update(['length_meters'=>$length,'calculated_area'=>$area]);foreach($d['stock_allocations']??[]as$s)DB::table('agricultural_service_stock_allocations')->insert([...$s,'general_agricultural_service_id'=>$id,'created_at'=>now(),'updated_at'=>now()]);}
    }
    private function detail(int$id):array{$fire=DB::table('firebreak_maintenances')->where('general_agricultural_service_id',$id)->first();return ['service'=>DB::table('general_agricultural_services')->find($id),'plots'=>DB::table('agricultural_service_plots')->where('general_agricultural_service_id',$id)->get(),'operators'=>DB::table('agricultural_service_operators')->where('general_agricultural_service_id',$id)->get(),'application'=>DB::table('agricultural_input_applications')->where('general_agricultural_service_id',$id)->first(),'stock_allocations'=>DB::table('agricultural_service_stock_allocations')->where('general_agricultural_service_id',$id)->get(),'firebreak'=>$fire,'firebreak_locations'=>$fire?DB::table('firebreak_maintenance_locations')->where('firebreak_maintenance_id',$fire->id)->get():[]];}
    private function rules():array{return ['service_category'=>['required',Rule::in(['SOIL_PREPARATION','INPUT_APPLICATION','FIREBREAK_MAINTENANCE'])],'agricultural_service_type_id'=>'required|exists:agricultural_service_types,id','crop_id'=>'required|exists:crops,id','culture_id'=>'nullable|exists:cultures,id','farm_id'=>'required|exists:farms,id','service_date'=>'required|date','started_at'=>'nullable|date','finished_at'=>'nullable|date|after_or_equal:started_at','notes'=>'nullable|string','plots'=>'required|array|min:1','plots.*.plot_field_id'=>'required|exists:plot_fields,id','plots.*.pass_number'=>'sometimes|integer|min:1','plots.*.notes'=>'nullable|string','operators'=>'required|array|min:1','operators.*.agricultural_service_type_id'=>'required|exists:agricultural_service_types,id','operators.*.agricultural_operator_id'=>'required|exists:agricultural_operators,id','operators.*.traction_fleet_id'=>'required|exists:fleets,id','operators.*.implement_fleet_id'=>'nullable|exists:fleets,id','operators.*.function'=>['required',Rule::in(['OPERATOR','SUPPORT','SUPERVISOR'])],'application'=>'required_if:service_category,INPUT_APPLICATION|array','application.product_id'=>'required_if:service_category,INPUT_APPLICATION|exists:products,id','application.rate_type'=>['required_if:service_category,INPUT_APPLICATION',Rule::in(['FIXED','VARIABLE'])],'application.fixed_rate'=>'required_if:application.rate_type,FIXED|nullable|numeric|gt:0','application.rate_unit'=>['required_if:service_category,INPUT_APPLICATION',Rule::in(['KG_HA','T_HA','L_HA'])],'application.plot_rates'=>'required_if:application.rate_type,VARIABLE|array','stock_allocations'=>'sometimes|array','stock_allocations.*.product_id'=>'required|exists:products,id','stock_allocations.*.product_stock_id'=>'required|exists:product_stocks,id','stock_allocations.*.agricultural_service_plot_id'=>'nullable|exists:agricultural_service_plots,id','stock_allocations.*.recommended_quantity'=>'sometimes|numeric|min:0','stock_allocations.*.real_quantity'=>'required|numeric|gt:0','firebreak'=>'required_if:service_category,FIREBREAK_MAINTENANCE|array','firebreak.width_meters'=>'nullable|numeric|gt:0','firebreak.actual_area'=>'nullable|numeric|gt:0','firebreak.locations'=>'required_if:service_category,FIREBREAK_MAINTENANCE|array|min:1','firebreak.locations.*.plot_field_id'=>'nullable|exists:plot_fields,id','firebreak.locations.*.description'=>'nullable|string','firebreak.locations.*.length_meters'=>'required|numeric|gt:0','firebreak.locations.*.width_meters'=>'required|numeric|gt:0'];}
}
