<?php
namespace App\Http\Controllers\Releases\Inventory;
use App\Http\Controllers\Controller;
use App\Services\Releases\Inventory\ProductStockService;
use App\Services\Shared\DocumentSequenceService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;
use Illuminate\Validation\ValidationException;
class ProductOutputController extends Controller {
 public function __construct(private readonly ProductStockService $stocks,private readonly DocumentSequenceService $numbers){}
 public function index(Request$r){return DB::table('product_outputs')->whereNull('deleted_at')->when($r->output_type,fn($q,$v)=>$q->where('output_type',$v))->when($r->status,fn($q,$v)=>$q->where('status',$v))->latest('output_date')->paginate(25);}
 public function show(int$output){return ['output'=>DB::table('product_outputs')->find($output),'items'=>DB::table('product_output_items')->where('product_output_id',$output)->get()];}
 public function store(Request$r){$d=$r->validate(['output_type'=>['required',Rule::in(['SALE','LOAN','DONATION'])],'output_date'=>'required|date','producer_id'=>'required|exists:producers,id','administrative_center_id'=>'required|exists:administrative_centers,id','cost_center_id'=>'required|exists:cost_centers,id','recipient_supplier_id'=>'nullable|exists:suppliers,id','recipient_name'=>'nullable|string','expected_return_date'=>'required_if:output_type,LOAN|nullable|date','observation'=>'nullable|string','items'=>'required|array|min:1','items.*.product_id'=>'required|exists:products,id','items.*.product_stock_id'=>'required|exists:product_stocks,id','items.*.quantity'=>'required|numeric|gt:0','items.*.unit_value'=>'sometimes|numeric|min:0']);return DB::transaction(function()use($d,$r){if(in_array($d['output_type'],['SALE','LOAN','DONATION'])&&empty($d['recipient_supplier_id'])&&blank($d['recipient_name']??null))throw ValidationException::withMessages(['recipient_name'=>['Informe o destinatário.']]);$id=DB::table('product_outputs')->insertGetId([...collect($d)->except('items')->all(),'output_number'=>$this->numbers->next('SAI'),'status'=>'DRAFT','created_by'=>$r->user()->id,'created_at'=>now(),'updated_at'=>now()]);foreach($d['items']as$i)DB::table('product_output_items')->insert([...$i,'product_output_id'=>$id,'total_value'=>round($i['quantity']*($i['unit_value']??0),2),'returned_quantity'=>0,'created_at'=>now(),'updated_at'=>now()]);return response()->json($this->show($id),201);});}
 public function confirm(Request$r,int$output){return DB::transaction(function()use($r,$output){$o=DB::table('product_outputs')->where('id',$output)->lockForUpdate()->firstOrFail();if($o->status!=='DRAFT')throw ValidationException::withMessages(['status'=>['Saída já processada.']]);foreach(DB::table('product_output_items')->where('product_output_id',$output)->get()as$i){$stock=DB::table('product_stocks')->where('id',$i->product_stock_id)->firstOrFail();if((int)$stock->product_id!==(int)$i->product_id)throw ValidationException::withMessages(['items'=>['Produto e posição de estoque incompatíveis.']]);$movement=$this->stocks->output(['product_id'=>$i->product_id,'stock_location_id'=>$stock->stock_location_id,'batch'=>$stock->batch,'treatment_status'=>$stock->treatment_status,'quantity'=>$i->quantity,'unit_value'=>$i->unit_value,'movement_type'=>'PRODUCT_'.$o->output_type,'source_type'=>'ProductOutput','source_id'=>$output,'created_by'=>$r->user()->id]);DB::table('product_output_items')->where('id',$i->id)->update(['stock_movement_id'=>$movement]);}DB::table('product_outputs')->where('id',$output)->update(['status'=>'CONFIRMED','confirmed_by'=>$r->user()->id,'confirmed_at'=>now(),'updated_at'=>now()]);return $this->show($output);});}
 public function returnLoan(Request$r,int$output){$d=$r->validate(['return_date'=>'required|date','reason'=>'nullable|string','items'=>'required|array|min:1','items.*.product_output_item_id'=>'required|distinct|exists:product_output_items,id','items.*.quantity'=>'required|numeric|gt:0']);return DB::transaction(function()use($d,$r,$output){$o=DB::table('product_outputs')->where('id',$output)->where('output_type','LOAN')->lockForUpdate()->firstOrFail();if(!in_array($o->status,['CONFIRMED','PARTIALLY_RETURNED']))throw ValidationException::withMessages(['status'=>['Empréstimo não está disponível para devolução.']]);$rid=DB::table('product_output_returns')->insertGetId(['return_number'=>$this->numbers->next('EMP-RET'),'product_output_id'=>$output,'return_date'=>$d['return_date'],'reason'=>$d['reason']??null,'created_by'=>$r->user()->id,'created_at'=>now(),'updated_at'=>now()]);foreach($d['items']as$x){$i=DB::table('product_output_items')->where('id',$x['product_output_item_id'])->where('product_output_id',$output)->lockForUpdate()->firstOrFail();if((float)$i->returned_quantity+(float)$x['quantity']>(float)$i->quantity)throw ValidationException::withMessages(['items'=>['Retorno superior ao saldo emprestado.']]);$stock=DB::table('product_stocks')->find($i->product_stock_id);$movement=$this->stocks->entry(['product_id'=>$i->product_id,'stock_location_id'=>$stock->stock_location_id,'batch'=>$stock->batch,'treatment_status'=>$stock->treatment_status,'quantity'=>$x['quantity'],'unit_value'=>$i->unit_value,'movement_type'=>'LOAN_RETURN','source_type'=>'ProductOutputReturn','source_id'=>$rid,'created_by'=>$r->user()->id]);DB::table('product_output_return_items')->insert(['product_output_return_id'=>$rid,'product_output_item_id'=>$i->id,'quantity'=>$x['quantity'],'stock_movement_id'=>$movement,'created_at'=>now(),'updated_at'=>now()]);DB::table('product_output_items')->where('id',$i->id)->increment('returned_quantity',$x['quantity']);}$items=DB::table('product_output_items')->where('product_output_id',$output)->get();$status=$items->every(fn($i)=>(float)$i->returned_quantity>=(float)$i->quantity)?'RETURNED':'PARTIALLY_RETURNED';DB::table('product_outputs')->where('id',$output)->update(['status'=>$status,'updated_at'=>now()]);return $this->show($output);});}
}
