<?php
namespace App\Http\Controllers\Releases\Fiscal;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;
class FiscalImportController extends Controller {
 public function preview(Request$r){$r->validate(['xml'=>'required|file|max:10240']);$path=$r->file('xml')->getRealPath();$hash=hash_file('sha256',$path);if(DB::table('entry_invoice_import_batches')->where('file_hash',$hash)->exists())throw ValidationException::withMessages(['xml'=>['Este arquivo já foi importado.']]);$xml=simplexml_load_file($path);if(!$xml)throw ValidationException::withMessages(['xml'=>['XML inválido.']]);$xml->registerXPathNamespace('n','http://www.portalfiscal.inf.br/nfe');$get=fn(string$x)=>(string)(($xml->xpath($x)[0]??''));$snapshot=['access_key'=>preg_replace('/^NFe/','',$get('//*[local-name()="infNFe"]/@Id')),'invoice_number'=>$get('//*[local-name()="ide"]/*[local-name()="nNF"]'),'series'=>$get('//*[local-name()="ide"]/*[local-name()="serie"]'),'supplier_cnpj'=>$get('//*[local-name()="emit"]/*[local-name()="CNPJ"]')];$supplier=DB::table('suppliers')->where('cpf_cnpj',$snapshot['supplier_cnpj'])->first();$id=DB::table('entry_invoice_import_batches')->insertGetId(['file_name'=>$r->file('xml')->getClientOriginalName(),'file_hash'=>$hash,'status'=>'PENDING','document_snapshot'=>json_encode($snapshot),'warnings'=>null,'created_by'=>$r->user()->id,'created_at'=>now(),'updated_at'=>now()]);foreach($xml->xpath('//*[local-name()="det"]')?:[]as$det){$code=(string)($det->xpath('.//*[local-name()="cProd"]')[0]??'');$description=(string)($det->xpath('.//*[local-name()="xProd"]')[0]??'');$relation=$supplier?DB::table('supplier_products')->where('supplier_id',$supplier->id)->where('product_code',$code)->where('status','A')->first():null;DB::table('entry_invoice_import_items')->insert(['entry_invoice_import_batch_id'=>$id,'supplier_id'=>$supplier->id??null,'supplier_product_code'=>$code,'description'=>$description,'ean'=>(string)($det->xpath('.//*[local-name()="cEAN"]')[0]??''),'ncm'=>(string)($det->xpath('.//*[local-name()="NCM"]')[0]??''),'product_id'=>$relation->product_id??null,'supplier_product_id'=>$relation->id??null,'quantity'=>(float)($det->xpath('.//*[local-name()="qCom"]')[0]??0),'unit_value'=>(float)($det->xpath('.//*[local-name()="vUnCom"]')[0]??0),'status'=>$relation?'MATCHED':'UNMATCHED','created_at'=>now(),'updated_at'=>now()]);}return response()->json(['batch'=>DB::table('entry_invoice_import_batches')->find($id),'items'=>DB::table('entry_invoice_import_items')->where('entry_invoice_import_batch_id',$id)->get()],201);}
 public function linkProduct(Request$r,int$importItem){$d=$r->validate(['product_id'=>'required|exists:products,id']);return DB::transaction(function()use($d,$r,$importItem){$item=DB::table('entry_invoice_import_items')->where('id',$importItem)->lockForUpdate()->firstOrFail();if(!$item->supplier_id)throw ValidationException::withMessages(['supplier_id'=>['Relacione primeiro o fornecedor do XML.']]);$relation=DB::table('supplier_products')->where('supplier_id',$item->supplier_id)->where('product_code',$item->supplier_product_code)->first();if($relation)DB::table('supplier_products')->where('id',$relation->id)->update(['product_id'=>$d['product_id'],'status'=>'A','deleted_at'=>null,'updated_at'=>now()]);else{$id=DB::table('supplier_products')->insertGetId(['supplier_id'=>$item->supplier_id,'product_id'=>$d['product_id'],'product_code'=>$item->supplier_product_code,'volume'=>1,'status'=>'A','created_at'=>now(),'updated_at'=>now()]);$relation=DB::table('supplier_products')->find($id);}DB::table('entry_invoice_import_items')->where('id',$importItem)->update(['product_id'=>$d['product_id'],'supplier_product_id'=>$relation->id,'status'=>'MATCHED','linked_by'=>$r->user()->id,'linked_at'=>now(),'updated_at'=>now()]);return DB::table('entry_invoice_import_items')->find($importItem);});}
}
