<?php
namespace App\Http\Controllers\Releases\Fiscal;
use App\Http\Controllers\Controller;
use App\Services\Releases\Inventory\ProductStockService;
use App\Services\Shared\DocumentSequenceService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;
class PurchaseReturnController extends Controller {
 public function __construct(private readonly ProductStockService $stocks,private readonly DocumentSequenceService $numbers){}
 public function index(Request$r){return DB::table('purchase_returns')->when($r->entry_invoice_id,fn($q,$v)=>$q->where('entry_invoice_id',$v))->when($r->status,fn($q,$v)=>$q->where('status',$v))->latest('return_date')->paginate(25);}
 public function show(int$purchaseReturn){return ['return'=>DB::table('purchase_returns')->find($purchaseReturn),'items'=>DB::table('purchase_return_items')->where('purchase_return_id',$purchaseReturn)->get()];}
 public function store(Request$r){$d=$r->validate(['entry_invoice_id'=>'required|exists:entry_invoices,id','return_date'=>'required|date','reason'=>'required|string','items'=>'required|array|min:1','items.*.entry_invoice_item_id'=>'required|exists:entry_invoice_items,id','items.*.product_stock_id'=>'required|exists:product_stocks,id','items.*.quantity'=>'required|numeric|gt:0']);return DB::transaction(function()use($d,$r){$id=DB::table('purchase_returns')->insertGetId(['return_number'=>$this->numbers->next('DEV'),'entry_invoice_id'=>$d['entry_invoice_id'],'return_date'=>$d['return_date'],'reason'=>$d['reason'],'total_value'=>0,'status'=>'DRAFT','created_by'=>$r->user()->id,'created_at'=>now(),'updated_at'=>now()]);$total=0;foreach($d['items']as$i){$item=DB::table('entry_invoice_items')->where('id',$i['entry_invoice_item_id'])->where('entry_invoice_id',$d['entry_invoice_id'])->firstOrFail();$available=(float)$item->quantity-(float)$item->returned_quantity;if($i['quantity']>$available)throw ValidationException::withMessages(['items'=>['Quantidade devolvida superior à quantidade disponível da nota.']]);$value=round($i['quantity']*$item->unit_value,2);$total+=$value;DB::table('purchase_return_items')->insert([...$i,'purchase_return_id'=>$id,'unit_value'=>$item->unit_value,'total_value'=>$value,'created_at'=>now(),'updated_at'=>now()]);}DB::table('purchase_returns')->where('id',$id)->update(['total_value'=>$total]);return response()->json($this->show($id),201);});}
 public function confirm(Request$r,int$purchaseReturn){return DB::transaction(function()use($r,$purchaseReturn){$return=DB::table('purchase_returns')->where('id',$purchaseReturn)->lockForUpdate()->firstOrFail();if($return->status!=='DRAFT')throw ValidationException::withMessages(['status'=>['Devolução já processada.']]);foreach(DB::table('purchase_return_items')->where('purchase_return_id',$purchaseReturn)->get()as$i){$item=DB::table('entry_invoice_items')->where('id',$i->entry_invoice_item_id)->lockForUpdate()->firstOrFail();if((float)$item->returned_quantity+(float)$i->quantity>(float)$item->quantity)throw ValidationException::withMessages(['items'=>['A devolução acumulada ultrapassa a entrada.']]);$stock=DB::table('product_stocks')->find($i->product_stock_id);$this->stocks->output(['product_id'=>$item->product_id,'stock_location_id'=>$stock->stock_location_id,'batch'=>$stock->batch,'treatment_status'=>$stock->treatment_status,'quantity'=>$i->quantity,'unit_value'=>$i->unit_value,'movement_type'=>'PURCHASE_RETURN','source_type'=>'PurchaseReturn','source_id'=>$purchaseReturn,'created_by'=>$r->user()->id]);DB::table('entry_invoice_items')->where('id',$item->id)->update(['returned_quantity'=>DB::raw('returned_quantity + '.(float)$i->quantity),'status'=>(float)$item->returned_quantity+(float)$i->quantity>=(float)$item->quantity?'RETURNED':'PARTIALLY_RETURNED']);}$invoiceItems=DB::table('entry_invoice_items')->where('entry_invoice_id',$return->entry_invoice_id)->get();$status=$invoiceItems->every(fn($i)=>(float)$i->returned_quantity>=(float)$i->quantity)?'RETURNED':'PARTIALLY_RETURNED';DB::table('entry_invoices')->where('id',$return->entry_invoice_id)->update(['status'=>$status]);DB::table('purchase_returns')->where('id',$purchaseReturn)->update(['status'=>'CONFIRMED','confirmed_by'=>$r->user()->id,'confirmed_at'=>now(),'updated_at'=>now()]);return $this->show($purchaseReturn);});}
}
